ARG BUN_VERSION="1.2"

FROM oven/bun:${BUN_VERSION}-slim AS base
WORKDIR /app

ARG BUN_VERSION
RUN echo "Using bun ${BUN_VERSION}-slim"

ARG REPOSITORY
ARG PREVIEW_SITE
ARG KEYSTATIC_SKIP
ARG BRAND_NAME
ARG BRAND_DESCRIPTION
ARG BRAND_LOGO
ARG BRAND_TWITTER
ARG EMAIL_USER
ARG EMAIL_TARGET

ENV ASTRO_TELEMETRY_DISABLED=1
ENV REPOSITORY=$REPOSITORY
ENV KEYSTATIC_SKIP=$KEYSTATIC_SKIP
ENV BRAND_NAME=$BRAND_NAME
ENV BRAND_DESCRIPTION=$BRAND_DESCRIPTION
ENV BRAND_LOGO=$BRAND_LOGO
ENV BRAND_TWITTER=$BRAND_TWITTER
ENV EMAIL_USER=$EMAIL_USER
ENV EMAIL_TARGET=$EMAIL_TARGET

COPY package.json bun.lock ./

FROM base AS deps
RUN bun install

FROM deps AS build
COPY . .
RUN bun run build

FROM base AS runtime
COPY --from=build /app .

ENV HOST=0.0.0.0
ENV PORT=4321
CMD ["bun", "run", "dist/server/entry.mjs"]
