ARG BUN_VERSION="1.2"

FROM oven/bun:${BUN_VERSION}-slim AS base
WORKDIR /app

ARG BUN_VERSION
RUN echo "Using bun ${BUN_VERSION}-slim"

ARG PREVIEW_SITE
ARG REPO_OWNER
ARG REPO_NAME
ARG KEYSTATIC_GITHUB_CLIENT_ID
ARG KEYSTATIC_GITHUB_CLIENT_SECRET
ARG KEYSTATIC_SECRET
ARG PUBLIC_KEYSTATIC_GITHUB_APP_SLUG
ARG BRAND_NAME
ARG BRAND_DESCRIPTION
ARG BRAND_LOGO
ARG BRAND_TWITTER
ARG RESEND_API_KEY
ARG EMAIL_USER
ARG EMAIL_TARGET

ENV ASTRO_TELEMETRY_DISABLED=1
ENV PREVIEW_SITE=$PREVIEW_SITE
ENV REPO_OWNER=$REPO_OWNER
ENV REPO_NAME=$REPO_NAME
ENV KEYSTATIC_GITHUB_CLIENT_ID=$KEYSTATIC_GITHUB_CLIENT_ID
ENV KEYSTATIC_GITHUB_CLIENT_SECRET=$KEYSTATIC_GITHUB_CLIENT_SECRET
ENV KEYSTATIC_SECRET=$KEYSTATIC_SECRET
ENV PUBLIC_KEYSTATIC_GITHUB_APP_SLUG=$PREVPUBLIC_KEYSTATIC_GITHUB_APP_SLUGEW_SITE
ENV BRAND_NAME=$BRAND_NAME
ENV BRAND_DESCRIPTION=$BRAND_DESCRIPTION
ENV BRAND_LOGO=$BRAND_LOGO
ENV BRAND_TWITTER=$BRAND_TWITTER
ENV RESEND_API_KEY=$RESEND_API_KEY
ENV EMAIL_USER=$EMAIL_USER
ENV EMAIL_TARGET=$EMAIL_TARGET

COPY package.json bun.lock ./

FROM base AS deps
RUN bun install

FROM deps AS build
COPY . .
RUN bun run build

FROM base AS runtime
COPY --from=build /app .

ENV HOST=0.0.0.0
ENV PORT=4321
CMD ["bun", "run", "dist/server/entry.mjs"]
