name: ci

on:
  push:
    # branches:
    #   - main

jobs:
  build:
    environment: Production
    runs-on: ubuntu-latest
    steps:
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: registry.work.soren.codes
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: registry.work.soren.codes/portfolio:latest
          build-args: |
            REPOSITORY=${ GITHUB_REPOSITORY }
            PREVIEW_SITE=${{ secrets.PREVIEW_SITE }}
            KEYSTATIC_GITHUB_CLIENT_ID=${{ secrets.KEYSTATIC_GITHUB_CLIENT_ID }}
            KEYSTATIC_GITHUB_CLIENT_SECRET=${{ secrets.KEYSTATIC_GITHUB_CLIENT_SECRET }}
            KEYSTATIC_SECRET=${{ secrets.KEYSTATIC_SECRET }}
            PUBLIC_KEYSTATIC_GITHUB_APP_SLUG=${{ secrets.PUBLIC_KEYSTATIC_GITHUB_APP_SLUG }}
            RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}
            EMAIL_USER=${{ secrets.EMAIL_USER }}
            EMAIL_TARGET=${{ secrets.EMAIL_TARGET }}
            BRAND_NAME=${{ vars.BRAND_NAME }}
            BRAND_DESCRIPTION=${{ vars.BRAND_DESCRIPTION }}
            BRAND_LOGO=${{ vars.BRAND_LOGO }}
            BRAND_TWITTER=${{ vars.BRAND_TWITTER }}
